project_id = "sdzqvgtqzsgmhgvkmnkf"

[functions.send-deposit-notification]
verify_jwt = false

[functions.send-sponsorship-notification]
verify_jwt = false

[functions.invite-user]
verify_jwt = false
